pipeline:
  build-image:
    image: docker
    commands:
      - docker build . -f Dockerfile.test -t gh_compare:${DRONE_BUILD_NUMBER} -t gh_compare:lastest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  test:
    image: "gh_compare:lastest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - "/app/run.sh test"