pipeline:
  build-image:
    image: docker
    commands:
      # Build development target, which includes xdebug.
      # Tag with both api-build:<build_number> and api-build:latest.
      # The <build_number> tag will be removed after the build
      # and the latest tag will stay as a cache.
      - docker build . -f Dockerfile.test -t gh_compare:${DRONE_BUILD_NUMBER} -t gh_compare:lastest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  test:
    image: "gh_compare:lastest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - "test"